# user on your local machine
localhost_user: yourLocalUser

# local config ssh file
config_file: ".ssh/config"

# any name for your server
server_name: YourAnyNameForServer

# domain or ip of your remote server
remote_host: "111.111.111.111"

root_user: root
root_key_name: "{{root_user}}_{{ server_name }}"
root_private_key_file: ".ssh/{{ root_key_name }}"
root_public_key_file: ".ssh/{{ root_key_name }}.pub"

# wireguard
wg_path: "/etc/wireguard"
wg_server_private_key_file: "{{ wg_path }}/privatekey"
wg_server_public_key_file: "{{ wg_path }}/publickey"

wg_server_ip: "10.0.0.1/24"
wg_server_port: 51830
wg_server_eth_adapter: "eth0"

wg_clients:
  - name: client1
  - name: client2
  - name: client3

wg_base_client_ip: "10.0.0.2"
wg_client_subnet: "/32"

wg_client_dns: "8.8.8.8"
wg_conf_dest_dir: "/home/yourOwnUserFolder/conf_files/"
wg_conf_client_AllowedIPs: "0.0.0.0/0"
wg_conf_client_PersistentKeepalive: 20
