---
- name: "Revert SSH configuration changes on localhost for the {{ localhost_user }}"
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: "Get user information"
      ansible.builtin.user:
        name: "{{ localhost_user }}"
      register: user_info

    - name: "Ensure .ssh directory exists"
      ansible.builtin.file:
        path: "{{ user_info.home }}/.ssh"
        state: directory
        mode: 0700

    - name: "Remove SSH configuration for the {{ localhost_user }}"
      ansible.builtin.blockinfile:
        path: "{{ lookup('env', 'HOME') }}/.ssh/config"
        state: absent
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ server_name }}"

    - name: "Remove public and private keys for the remote server"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ user_info.home}}/{{root_private_key_file }}"
        - "{{ user_info.home}}/{{root_public_key_file }}"

    - name: "Remove server from known_hosts for {{ remote_host }}"
      ansible.builtin.shell: "ssh-keygen -R {{ remote_host }}"
